CREATE TABLE CARD (
ID INT NOT NULL AUTO_INCREMENT
, BANK_NAME VARCHAR(60) NOT NULL
, CARD_NUMBER VARCHAR(60) NOT NULL    
, DATE_EXPIRE DATE
, VERSION INT NOT NULL DEFAULT 0
, UNIQUE UQ_CARD_1 (CARD_NUMBER)
, PRIMARY KEY (ID)
);